import React from 'react';

export default function Home() {
    return (
        <React.Fragment>
            <h1>History of Pokemons</h1>
            <p>In the first part of the Original Series, Ash Ketchum is allowed to start his journey in the world of Pokémon and dreams of becoming a Pokémon master, but on the day he is to receive his first Pokémon, Ash oversleeps and wakes up in a panic, running into Gary Oak, who becomes Ash's rival. Professor Oak, the local Pokémon researcher, has already given away the three Pokémon (Bulbasaur, Charmander and Squirtle) he entrusts to new Pokémon Trainers when Ash finally reaches Oak's Lab. The only Pokémon that he has left is a Pikachu, which he gives to Ash. Determined to make it on his journey, Ash does his best to befriend Pikachu, but it refused to trust him and chooses to stay out of the Poké Ball, even attacking Ash with its electric powers. It is only after Ash protects Pikachu from a group of angry Spearow that Pikachu realizes how much Ash cares.

Along the way, Ash makes many human and Pokémon friends as he works his way through the ranks of the world's many Pokémon Leagues. Through the Kanto Region, Ash befriends Water Pokémon trainer and erstwhile Cerulean City Gym Leader Misty and Pewter City Gym Leader and Pokémon Breeder Brock, and all the while thwarting the plans of Jessie, James, and Meowth, low-ranking members of the criminal organization Team Rocket who want to steal Ash's Pikachu and any other rare Pokémon they come across. Giovanni, Team Rocket's Boss introduced three new high-ranking members of Team Rocket; Cassidy, Butch, and Raticate, who want to kidnap Pokémon so they can use their moves. Ash wins eight badges from Gym Leaders in the Kanto region to compete in the Indigo Conference League. Gary loses in the fourth round, placing him in the Top 32. Ash makes it to the Top 16, but loses to Ritchie in the fifth round. Also, Ritchie loses to Assunta in the sixth round, placing him in the Top 8.

When the group travels to the Orange Islands, Ash releases his Pidgeot, and Brock decides to stay with the local professor, Ivy, leaving Ash and Misty to continue traveling together. After a while, they meet and begin traveling with Pokémon Watcher and artist Tracey Sketchit. Ash defeats four Gym Leaders in the Orange Islands, and becomes the champion of the Orange League. Once they reach Pallet Town in Kanto, Tracey decides to stay with Professor Oak and Brock rejoins the group. Ash loses to Gary before leaving the Kanto region. Ash releases Lapras. Following this, the trio continues on their way to the Johto region.

In the second part of the Original Series, Ash explores the new adventures in the Johto region with Misty and Brock. Ash gives the GS Ball to the Apricorn Poké Ball maker, Kurt. Ash's quest is to defeat the eight Gym Leaders in the Johto region and participate in the Silver Conference. Team Rocket's Jessie gains a Wobbuffet as a new partner. Ash beats Gary for the first time in the Silver Conference, placing him in the Top 16, but Ash loses to Harrison, in the quarterfinals, placing him in the Top 8. But also, Harrison loses to Jon Dickson, in the semifinals, placing him in the Top 4. Finally, Ash returns to the Kanto region to set sail in the Hoenn region. Misty returns to Cerulean City in Kanto to become the full-time Cerulean City Gym Leader and she got her bike fixed that has been destroyed in the beginning of Ash's quest.

Brock follows Ash to Hoenn and Ash gains two new companions, a Pokémon Coordinator May and her younger brother Max, and together they go on an adventure. May collects five ribbons to participate in the Hoenn Grand Festival, and the Kanto Grand Festival. Misty returns and later releases her Togepi, which has evolved to Togetic. Ash defeats all eight Hoenn gym leaders and participates in the Ever Grande Conference, but he loses to Tyson (Tetsuya), in the quarterfinals, placing him in the Top 8. In Pokémon: Battle Frontier (Japanese: ポケットモンスター バトルフロンティア編, Pocket Monsters: Episode Battle Frontier), Ash gets seven frontier symbols in Kanto, and wins the Battle Frontier. However, Ash declines the Battle Frontier Brian title, and decides to continue his Pokémon journey. Afterwards, Ash battles with his rival, Gary. After seeing Electivire, a Pokémon from the Sinnoh region he has never seen before, Ash decides to travel to Sinnoh, and Brock joins him.

Upon arrival in Sinnoh, Ash and Brock meet Dawn, another Pokémon Coordinator, who travels with them as they go through the Sinnoh region in an adventure. Dawn earns five ribbons to participate in the Sinnoh Grand Festival. Dawn loses to Zoey, placing her runner-up. Ash defeats all eight Sinnoh gym leaders to participate in the Lily of the Valley Conference, but he loses to Tobias, in the semifinals, placing him in the Top 4. Afterwards, Ash, his mother Delia and Professor Oak take a holiday to the far-off Unova Region, where he meets and travels with would-be Dragon Master Iris and Striaton City Gym Leader, Pokémon Connoisseur, and sometimes detective Cilan. After winning all eight Unova badges and thwarting the sinister Team Plasma, Ash, Iris, and Cilan travel throughout the eastern side of Unova to prepare for the Vertress Conference, but Ash loses to Cameron, in the quarterfinals, placing him in the Top 8. But also, Cameron loses to Virgil in the semifinals, placing him in the Top 4. Afterwards, Ash, Iris, and Cilan travel through the Decolore Islands before Ash makes his way back to Pallet Town and meet the investigative reporter Alexa, who is from the distant Kalos Region. Having arrived back in Kanto, Iris and Cilan travel to Johto whilst Ash and Alexa head to Kalos.

Ash and Alexa arrive in the Kalos region and Ash is itching to get started in earning his Gym badges. But after Alexa informs Ash that her sister, a Gym Leader, is currently absent, Ash travels to Lumiose City where he meets boy-genius Clemont and his younger sister Bonnie, unaware that Clemont is, in fact, Lumiose City's Gym Leader; a fact he tries his best to hide. Ash also reunites with Serena, a girl from Vaniville Town whom Ash had met in his childhood. Serena earns three keys to participate in the Pokémon Showcase. Serena loses to Aria, placing her runner-up. After traveling with Serena, Clemont, and Bonnie to prepare for the Lumiose Conference by defeating all eight Kalos gym leaders, Ash competes and advances all the way to the finals, where he loses to Alain, a temporary member of the evil Team Flare due to them misleading him. Once he discovers their true intentions, however, Alain reforms and joins Ash and his friends to stop Team Flare's plans. Bidding farewell to his friends in Kalos, Ash once again returns to Pallet Town.

In Pokémon the Series: Sun & Moon (Japanese: ポケットモンスター　サン＆ムーン Pocket Monsters Sun & Moon), Ash, Delia and her Mr. Mime are on vacation in the Alola region when Ash has an encounter with Tapu Koko, the guardian Pokémon of Melemele Island, who presents him with the Z-Ring, a device that, when paired with a special crystal, allows a Pokémon to unleash a powerful move when synchronized with its trainer. This leads him to stay in Alola and enroll at the local Pokémon school. When he decides to undertake the trials necessary to master the power of the Z-Ring, Ash's new classmates Lana, Mallow, Lillie, Sophocles and Kiawe decide to accompany him. Ash takes part in the island challenges, but Ash loses to Team Rocket members Jessie, James, Meowth, and Wobbuffet in a battle for the first time in his quest. But then later, Ash finally gains his first-ever official league victory at the Manalo Conference.

In the new series, Pokémon Journeys: The Series (Japanese: ポケットモンスター Pocket Monsters) focuses on all eight regions, including Galar, the setting of the Pokémon Sword and Shield games. Pikachu's backstory as a Pichu, and Ash's backstory when he was 6 years old missing Professor Oak's camp. Goh's backstory when he was 6 years old and he did attend Professor Oak's camp, and he saw Mew. It sees Ash and Pikachu travel to each of the regions, accompanied by Goh and his Scorbunny, which later evolves into Raboot. Currently, the supporting cast includes a girl named Chloe and her Yamper. As of now, Ash's team consists of Pikachu, Mr. Mime, Gengar, Dragonite, Lucario, and a Galarian Farfetch'd.</p>
        </React.Fragment>
    )
}
